name: dae_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.2.89
  - nibabel=3.2.1
  - numpy=1.20.3
  - python=3.7.11
  - pytorch=1.10.2
  - tqdm=4.62.3
  - scikit-image=0.19.1
  - scikit-learn=1.0.2
  - setuptools=59.5.0
  - pip:
    - tensorboard==2.5.0
